import type { Metadata } from "next";
import { Geist, Source_Code_Pro } from "next/font/google"
import "../styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ScrollToTop from "@/components/shared/scroll-to-top";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${geistSans.variable} ${sourceCodePro.variable}`}>
      <body className="bg-background antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
        <Suspense>
          <ScrollToTop />
        </Suspense>
      </body>
    </html>
  );
}
